# Generated by Django 2.2.15 on 2020-08-20 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0001_initial'),
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PietWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('historic', models.CharField(max_length=255)),
                ('deb', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cred', models.DecimalField(decimal_places=2, max_digits=100)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bka_piet_work_id', to='bank_account.BankAccount')),
                ('entity_piet_work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piet_work_entity_id', to='entities.Entities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piet_work_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PietWork',
                'verbose_name_plural': 'PietWorks',
                'ordering': ['id'],
            },
        ),
    ]
