# Generated by Django 2.2.15 on 2020-08-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piety_works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pietwork',
            name='commit',
            field=models.TextField(null=True),
        ),
    ]
