# Generated by Django 2.2.15 on 2020-08-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piety_works', '0002_pietwork_commit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pietwork',
            name='commit',
        ),
    ]
