# Generated by Django 2.2.15 on 2020-08-19 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0003_auto_20200818_2015'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('collection', models.DecimalField(decimal_places=2, max_digits=100)),
                ('delivered', models.DecimalField(decimal_places=2, max_digits=100)),
                ('complementos', models.DecimalField(decimal_places=2, max_digits=100)),
                ('deposits', models.DecimalField(decimal_places=2, max_digits=100)),
                ('looting', models.DecimalField(decimal_places=2, max_digits=100)),
                ('returned', models.DecimalField(decimal_places=2, max_digits=100)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=100)),
                ('entity_travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_id', to='entities.Entities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
                'ordering': ['id'],
            },
        ),
    ]
