# Generated by Django 2.2.15 on 2020-08-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travel_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
