# Generated by Django 2.2.15 on 2020-08-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travel_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='travel_entity_id',
            new_name='entity_id',
        ),
    ]
