# Generated by Django 2.2.15 on 2020-08-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('travel', '0003_auto_20200820_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='new',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='total',
        ),
        migrations.AddField(
            model_name='travel',
            name='entity_travel_id',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, related_name='travel_id', to='entities.Entities'),
            preserve_default=False,
        ),
    ]
