# Generated by Django 2.2.15 on 2020-08-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travel_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='commit',
        ),
    ]
