# Generated by Django 2.2.15 on 2020-08-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
