# Generated by Django 2.2.15 on 2020-08-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200817_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_of_birth',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
