# Generated by Django 2.2.15 on 2020-08-17 21:05

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200817_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, default=43998096957, help_text='Número para conato', max_length=31),
            preserve_default=False,
        ),
    ]
