# Generated by Django 2.2.15 on 2020-08-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('accounts', '0008_auto_20200817_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entitie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Entities'),
        ),
    ]
