# Generated by Django 2.2.15 on 2020-08-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_entitie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='entitie_id',
        ),
    ]
