# Generated by Django 2.2.15 on 2020-08-16 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=30)),
                ('doc_id', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baccount_apiuser_name', to='api_server.APIUser')),
            ],
            options={
                'verbose_name': 'BAccount',
                'verbose_name_plural': 'BAccounts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('collection', models.DecimalField(decimal_places=2, max_digits=100)),
                ('delivered', models.DecimalField(decimal_places=2, max_digits=100)),
                ('complementos', models.DecimalField(decimal_places=2, max_digits=100)),
                ('deposits', models.DecimalField(decimal_places=2, max_digits=100)),
                ('looting', models.DecimalField(decimal_places=2, max_digits=100)),
                ('returned', models.DecimalField(decimal_places=2, max_digits=100)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_apiuser_name', to='api_server.APIUser')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BWorkOfPiety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('historic', models.CharField(max_length=255)),
                ('deb', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cred', models.DecimalField(decimal_places=2, max_digits=100)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bworkofpiety_apiuser_name_baccount_account', to='api_server.BAccount')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bworkofpiety_apiuser_name', to='api_server.APIUser')),
            ],
            options={
                'verbose_name': 'BWorkOfPiety',
                'verbose_name_plural': 'BWorkOfPietys',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BAccountMovimant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('historic', models.CharField(max_length=255)),
                ('deb', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cred', models.DecimalField(decimal_places=2, max_digits=100)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baccountmovimant_baccount_account', to='api_server.BAccount')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baccountmovimant_apiuser_name', to='api_server.APIUser')),
            ],
            options={
                'verbose_name': 'BAccountMovimant',
                'verbose_name_plural': 'BAccountMovimants',
                'ordering': ['id'],
            },
        ),
    ]
