# Generated by Django 2.2.15 on 2020-08-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('doc_id', models.CharField(max_length=255, unique=True)),
                ('row', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('user_pass', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'APIUser',
                'verbose_name_plural': 'APIUsers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiuser_name', to='api_server.APIUser')),
            ],
            options={
                'verbose_name': 'BAccount',
                'verbose_name_plural': 'BAccounts',
                'ordering': ['id'],
            },
        ),
    ]
