# Generated by Django 2.2.15 on 2020-08-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baccount',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baccount_apiuser_name', to='api_server.APIUser'),
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('collection', models.DecimalField(decimal_places=2, max_digits=2)),
                ('delivered', models.DecimalField(decimal_places=2, max_digits=2)),
                ('complementos', models.DecimalField(decimal_places=2, max_digits=2)),
                ('deposits', models.DecimalField(decimal_places=2, max_digits=2)),
                ('looting', models.DecimalField(decimal_places=2, max_digits=2)),
                ('returned', models.DecimalField(decimal_places=2, max_digits=2)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=2)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_apiuser_name', to='api_server.APIUser')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BWorkOfPiety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('historic', models.CharField(max_length=255)),
                ('deb', models.DecimalField(decimal_places=2, max_digits=2)),
                ('cred', models.DecimalField(decimal_places=2, max_digits=2)),
                ('value_total', models.DecimalField(decimal_places=2, max_digits=2)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bworkofpiety_apiuser_name_baccount_account', to='api_server.BAccount')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bworkofpiety_apiuser_name', to='api_server.APIUser')),
            ],
            options={
                'verbose_name': 'BWorkOfPiety',
                'verbose_name_plural': 'BWorkOfPietys',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BAccountMovimant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('historic', models.CharField(max_length=255)),
                ('deb', models.DecimalField(decimal_places=2, max_digits=2)),
                ('cred', models.DecimalField(decimal_places=2, max_digits=2)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baccountmovimant_baccount_account', to='api_server.BAccount')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baccountmovimant_apiuser_name', to='api_server.APIUser')),
            ],
            options={
                'verbose_name': 'BAccountMovimant',
                'verbose_name_plural': 'BAccountMovimants',
                'ordering': ['id'],
            },
        ),
    ]
