# Generated by Django 2.2.15 on 2020-08-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0003_auto_20200813_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bworkofpiety',
            name='value_total',
        ),
    ]
