# Generated by Django 2.2.15 on 2020-08-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0003_auto_20200815_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
