# Generated by Django 2.2.15 on 2020-08-16 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0005_auto_20200816_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baccount',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baccount_apiuser_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='baccountmovimant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baccountmovimant_apiuser_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bworkofpiety',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bworkofpiety_apiuser_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_apiuser_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='APIUser',
        ),
    ]
