# Generated by Django 2.2.15 on 2020-08-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0005_auto_20200813_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baccountmovimant',
            name='cred',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='baccountmovimant',
            name='deb',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='bworkofpiety',
            name='cred',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='bworkofpiety',
            name='deb',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='travel',
            name='collection',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='travel',
            name='complementos',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='travel',
            name='delivered',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='travel',
            name='deposits',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='travel',
            name='expenses',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='travel',
            name='looting',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='travel',
            name='returned',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
