# Generated by Django 2.2.15 on 2020-08-18 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20200818_2015'),
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='entity_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bka_entity_id', to='entities.Entities'),
            preserve_default=False,
        ),
    ]
