# Generated by Django 2.2.15 on 2020-08-19 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_account', '0002_bankaccount_entity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountMovimant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('historic', models.CharField(max_length=255)),
                ('deb', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cred', models.DecimalField(decimal_places=2, max_digits=100)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='bank_account.BankAccount')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bka_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BankAccountMovimant',
                'verbose_name_plural': 'BankAccountMovimants',
                'ordering': ['id'],
            },
        ),
    ]
