# Generated by Django 2.2.15 on 2020-08-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0004_auto_20200818_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='commit',
        ),
        migrations.RemoveField(
            model_name='bankaccountmovimant',
            name='commit',
        ),
    ]
