# Generated by Django 2.2.15 on 2020-08-19 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0005_auto_20200819_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountmovimant',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_moviment', to='bank_account.BankAccount'),
        ),
    ]
