# Generated by Django 2.2.15 on 2020-08-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_entity', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('document_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['id'],
                'unique_together': {('name', 'document_id')},
            },
        ),
    ]
