# Generated by Django 2.2.15 on 2020-08-20 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criation', models.DateTimeField(auto_now_add=True)),
                ('actualization', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('type_entity', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('document_id', models.CharField(blank=True, max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entitie_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['id'],
                'unique_together': {('name', 'document_id')},
            },
        ),
    ]
