# Generated by Django 2.2.15 on 2020-08-18 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='entitie_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
