# Generated by Django 2.2.15 on 2020-08-18 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_entities_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='actualization',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='criation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
