# Generated by Django 2.2.15 on 2020-08-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20200818_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='commit',
            field=models.TextField(null=True),
        ),
    ]
