# Generated by Django 2.2.15 on 2020-08-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_entities_commit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entities',
            name='commit',
        ),
    ]
