# Generated by Django 2.2.15 on 2020-08-19 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_remove_entities_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entitie_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
